### ISSUE TITLE
 @TaskAction annotation error with IncrementalTaskInputs in IncrementalTransformTask

### ISSUE THREAD

**Issue by ritick-plateron** [newrelic/newrelic-flutter-agent#106] opened 2024-08-04 21:14 UTC
I'm encountering a build error related to the New Relic Gradle plugin when building my Android application. The error message indicates that using the @TaskAction annotation on the IncrementalTransformTask.transform() method with IncrementalTaskInputs as a parameter is no longer valid.

**Steps to reproduce:**
Add the New Relic Gradle plugin to your Android project com.newrelic.agent.android:agent-gradle-plugin:7.5.0.
Attempt to build the project.

**Expected behavior:**
The project should build successfully without errors.

**Actual behavior:**
The build fails with the following error:
```
Cannot use @TaskAction annotation on method IncrementalTransformTask.transform() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```

Environment:
New Relic Gradle plugin version: 7.5.1.
Gradle version: 8.1
Android Gradle plugin version: 7.4.2

This issue might be caused by an incompatibility between the New Relic Gradle plugin and the Android Gradle plugin, potentially due to changes in the valid parameter types for @TaskAction methods. Updating the New Relic plugin to the latest version might resolve the problem.

Please investigate this issue and provide a fix or workaround.

Remember to:
Replace the bracketed information with your specific details.

**Comment by ndesai-newrelic** [comment] 2024-08-05 17:26
@ritick-plateron can you share sample app for this? Can you also share your flutter version and build.gradle file for this?

**Comment by ndesai-newrelic** [comment] 2024-08-21 15:15
@ritick-plateron we are unable to reproduce this. I am closing it .

**Closed by ndesai-newrelic** 2024-08-21 15:15 UTC
