### ISSUE TITLE
Android app crashes every time when launching in release mode

### ISSUE THREAD

**Issue by matthewfx** [newrelic/newrelic-flutter-agent#75] opened 2024-02-08 11:12 UTC
I have added new relic 1.0.6

When run in debug it works fine but when an aab or apk in release mode is made it crashes the app every single time when you launch it (on the splash screen).

I have Crashlytics too and that's what I see in logs there

```
Fatal Exception: java.lang.ExceptionInInitializerError
com.newrelic.agent.android.NullAgentImpl.getDeviceInformation (NullAgentImpl.java:4)
com.newrelic.agent.android.Agent.getDeviceInformation (Agent.java:4)
com.newrelic.agent.android.stats.StatsEngine$SupportabilityDecorator.lazyGet (StatsEngine.java)
com.newrelic.agent.android.stats.StatsEngine.s (StatsEngine.java:1)
com.newrelic.agent.android.NewRelic.enableFeature (NewRelic.java:23)
com.newrelic.newrelic_mobile.NewrelicMobilePlugin.onMethodCall (NewrelicMobilePlugin.java:1456)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.a (MethodChannel.java:18)
io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java:46)

Caused by java.lang.RuntimeException
Missing type parameter.
com.newrelic.agent.android.NullAgentImpl.getDeviceInformation (NullAgentImpl.java:4)
com.newrelic.agent.android.Agent.getDeviceInformation (Agent.java:4)
com.newrelic.agent.android.stats.StatsEngine$SupportabilityDecorator.lazyGet (StatsEngine.java)
com.newrelic.agent.android.stats.StatsEngine.s (StatsEngine.java:1)
com.newrelic.agent.android.NewRelic.enableFeature (NewRelic.java:23)
com.newrelic.newrelic_mobile.NewrelicMobilePlugin.onMethodCall (NewrelicMobilePlugin.java:1456)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.a (MethodChannel.java:18)
io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java:46)
io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0 (DartMessenger.java:46)
```
I have checked if I haven't missed anything from the setup but doesn't look like I have

**Comment by ndesai-newrelic** [comment] 2024-02-08 15:29
@matthewfx which device are you using? can you share sample app where we can reproduce the issue? we have 500+ apps already in production with this agent.

**Comment by matthewfx** [comment] 2024-02-08 20:00
It happens on all devices and emulators. Our app is a pretty mature and big project so I'm guessing maybe there is a clash with some other dependencies. Its size makes it hard for me to build a sample app atm. Do you have any clues what theoretically might be causing `NullAgentImpl.getDeviceInformation`?

**Comment by ndesai-newrelic** [comment] 2024-02-08 20:05
@matthewfx how are you starting your agent? can you share that?

**Comment by matthewfx** [comment] 2024-02-08 20:09
Sure: 
I'm calling this 
```
Future<void> _newRelicSetup(String appToken) async {
  final Config config = Config(accessToken: appToken);
  FlutterError.onError = NewrelicMobile.onError;
  await NewrelicMobile.instance.startAgent(config);
  NewrelicMobile.instance.recordCustomEvent('AppStarted');
}
```

among other things I call within `runZonedGuarded` closure.

**Comment by ndesai-newrelic** [comment] 2024-02-09 15:39
@matthewfx can you enable verbose logging and send agent logs ?

**Comment by matthewfx** [comment] 2024-02-19 04:03
Hi, I'm sorry but I went for a short holiday and only returned today. I will try to send it later this week.

**Comment by ndesai-newrelic** [comment] 2024-04-11 13:21
@matthewfx any update on this one? can i close the issue?

**Closed** 2024-08-12 16:10 UTC

**Comment by ismailyil** [comment] 2025-04-16 22:20
I had the same issue with my Flutter app — it worked fine in debug mode but crashed on startup in release mode after adding New Relic. The cause of error can be R8 minification/obfuscation, which was stripping or renaming critical New Relic classes. Preserve New Relic classes unobfuscated by adding proguardFiles to android/app/build.gradle .

```dart
-keep class com.newrelic.** { *; }
-dontwarn com.newrelic.**
-keepattributes *Annotation*, SourceFile, LineNumberTable
``` 
After applying these rules, the app worked correctly in release mode.
