### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by ashiq-mvp** [newrelic/newrelic-flutter-agent#109] opened 2024-09-05 08:17 UTC
`redirectDebugPrint() {
    if (_originalDebugPrint != null) return;
    _originalDebugPrint = debugPrint;
    debugPrint = (String? message, {int? wrapWidth}) {
      if (_originalDebugPrint != null) {
        logDebug(message!);
        // recordCustomEvent("Mobile Dart Console Events",
        //     eventAttributes: {"message": message});
        _originalDebugPrint!(message, wrapWidth: wrapWidth);
      }
    };
  }`

### **I am encountering a null check issue with the message variable due to the use of !. Could you please review the implementation of this package and let me know if I missed anything? Thank you!** @ndesai-newrelic

**Comment by ndesai-newrelic** [comment] 2024-09-05 15:43
@ashiq-mvp we will fix it our next release.

**Comment by ndesai-newrelic** [comment] 2024-09-17 14:39
@ashiq-mvp the issue is fixed in latest release.

**Closed by ndesai-newrelic** 2024-09-17 14:39 UTC
